version: '3.8'
services:
  db:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_DB: ${POSTGRES_DB:-todo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      # <Port exposed> : < POSTGRES Port running inside container>
      - '5432:5432'
    volumes:
      - postgres-db:/var/lib/postgres
volumes:
  postgres-db: